### ISSUE TITLE
How to run the project ?

### ISSUE THREAD

**Issue by flipmedia** [aswins/Mizhi#1]
Dear Aswin,
I downloaded your source code and try to run in my Ubuntu pc. But got output as 

insight@Inspiron:~/Downloads/Mizhi-master/src$ python start.py 
Enter the scanned image:
test.jpg
Traceback (most recent call last):
  File "start.py", line 18, in <module>
    binary_image.binarize()
  File "/home/insight/Downloads/Mizhi-master/src/binary.py", line 15, in binarize
    if(pix[x,y][0]>127 or pix[x,y][1]>127 or pix[x,y][2]>127):
TypeError: 'int' object has no attribute '__getitem__

Please let me know how I can run my malayalam containing images for OCR purpose.

Waiting Your fast reply.

Thanks
Anes
![test](https://cloud.githubusercontent.com/assets/610256/19961736/268ce2ce-a1da-11e6-8c50-e9f792957122.jpg)

**Comment by aswins** [comment]
Hi, This project is not actively maintained. You should probably look elsewhere for a working solution.

Also, the error here: https://github.com/aswins/Mizhi/blob/master/src/binary.py#L12 is
because the input to this program is expected to be an RGB image and not a grayscale one.
